name: Continuous Integration

on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  ci:
    name: Build and run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24

      - uses: pnpm/action-setup@v4
        with:
          run_install: true

      - name: Install Playwright browsers
        run: pnpm exec playwright install --with-deps chromium

      - name: Run all tests
        run: pnpm run ci
