name: build and deploy

on:
  push:
    branches: ['main']

jobs:
  ci:
    name: build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: pnpm/action-setup@v4
        with:
          run_install: true
        env:
          NPM_TOKEN: xxx

      - uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Run all checks
        run: xvfb-run pnpm run ci
        env:
          NPM_TOKEN: xxx

  publish:
    name: publish packages
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          always-auth: true
          registry-url: https://registry.npmjs.org
          scope: '@spearwolf'

      - uses: pnpm/action-setup@v4
        with:
          run_install: true
        env:
          NPM_TOKEN: xxx

      - run: pnpm run publishNpmPkg
        name: Publish npm packages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
